### ISSUE TITLE
Cold you release a prebuild apk?

### ISSUE THREAD

**Issue by GameOverFlowChart** [BBuf/run-rwkv-world-4-in-mlc-llm#1]
As the title says, an apk release would make it very simple to test out the model. One which can run the 3b and 7b rwkv-4 world models in best case.

**Comment by BBuf** [comment]
Sorry, I cannot do this because the built APK is not working on my phone, and the reason for this is unknown. Please refer to the following page for reference: https://github.com/mlc-ai/mlc-llm/issues/862

**Comment by BBuf** [comment]
@GameOverFlowChart you can use https://github.com/BBuf/run-rwkv-world-4-in-mlc-llm/releases/download/v1.0.0/app-debug.apk now.

**Comment by GameOverFlowChart** [comment]
Thanks I will have a look at that. It's MLC? I hope I can install it side by side to the official app, if not, it would be nice if the projects would get merged.
