### ISSUE TITLE
the tokenizer

### ISSUE THREAD

**Issue by KhalidAlt** [BBuf/run-rwkv-world-4-in-mlc-llm#2]
Hi, 

I would like to ask is there a way to load the tokenizer using Autotokenizer from Huggingface. Also I noticed that when I downloaed the tokenizer from [this link](https://github.com/BBuf/run-rwkv-world-4-in-mlc-llm/archive/refs/tags/v1.0.0.tar.gz), I did not find a file named "tokenizer_model.zip".

 I tried to change the extension of the file from .tar.gz to .zip and extracted it to a folder named "tokenizer_model". However, I was unable  to load the tokenizer using Huggingface.
 
 Could you provide any guidance on this matter?

Thank you.

**Comment by BBuf** [comment]
The HuggingFace version of the RWKV "world" model tokenizer is currently under development and is not supported yet.

**Comment by BBuf** [comment]
please see: https://github.com/BBuf/RWKV-World-HF-Tokenizer

**Comment by BBuf** [comment]
or you can see: https://github.com/huggingface/transformers/pull/26963
